export const images = [
  {
    id: 1,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740828/group8-imgery/001_a7ge3v.png",
    title: "Kabe",
    role: "Lead Artist",
    text: "Award-winning illustrator with an international portfolio including clients in film, publishing & the gaming industry. When he's not creating awesome artwork, Kabe is wreaking havoc in the world of table-top RPGs.",
  },
  {
    id: 2,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740828/group8-imgery/002_ptos2c.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 3,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740828/group8-imgery/003_rxbdlz.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 4,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740828/group8-imgery/004_xamlwm.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 5,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740828/group8-imgery/005_xydasr.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 6,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740828/group8-imgery/006_a4vl0h.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 7,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740829/group8-imgery/007_de23xf.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 8,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740830/group8-imgery/008_a4n4ig.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 9,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740830/group8-imgery/009_hueyvd.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
  {
    id: 10,
    link: "https://res.cloudinary.com/frank2021/image/upload/v1672740829/group8-imgery/010_aacx5q.png",
    title: "WEDGE",
    role: "CCO",
    text: "Wedge lives for the network. From selling gaming platforms to Mercedes F1, Guinness and UEFA, to ML software for some of the biggest Telecomms companies like Verizon, Vodafone, and T-mobile. This guy knows how to build profile and enjoys nothing more.",
  },
];
